version: "3.9"

services:
  db:
    image: postgres
    env_file: .env
    restart: always
    ports:
      - "5432:5432"
  redis:
    image: redis
  client:
    build: .
    env_file: .env
    command: yarn workspace @heimdall/client dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
  sync_server:
    build: .
    env_file: .env
    command: yarn workspace @heimdall/sync_server dev
    volumes:
      - .:/app
  api:
    build: .
    env_file: .env
    command: yarn workspace @heimdall/api dev
    ports:
      - "5000:5000"
    volumes:
      - .:/app
